name: plutonic
base: core22
version: '1.0.1'
summary: Suikalike game where you shoot planets in space
description: |
  Suikalike game where you shoot planets in space

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

apps:
  plutonic:
    command: plutonic
    extensions: [gnome]
    plugs: [home, network, removable-media, unity7]

parts:
  plutonic:
    plugin: dump
    source: ./builds/
    source-type: local
    stage-packages:
      - libglu1-mesa
      - libxcursor1
      - libxinerama1
      - libxrandr2
      - libxi6
      - libpulse0
    override-build: |
      craftctl default
      chmod +x $SNAPCRAFT_PART_INSTALL/plutonic

layout:
  /usr/share/plutonic:
    bind: $SNAP/usr/share/plutonic
